#ifndef OWL_INCLUDE_CODE_H_
#define OWL_INCLUDE_CODE_H_

enum owl_code {
  OWL_SUCCESS,
  OWL_ERROR_BAD_ALLOC,
  OWL_ERROR_BAD_INIT,
  OWL_ERROR_BAD_HANDLE,
  OWL_ERROR_BAD_PTR,
  OWL_ERROR_OUT_OF_BOUNDS,
  OWL_ERROR_OUTDATED_SWAPCHAIN,
  OWL_ERROR_INVALID_MEM_TYPE,
  OWL_ERROR_OUT_OF_SPACE,
  OWL_ERROR_NO_SUITABLE_DEVICE,
  OWL_ERROR_NO_SUITABLE_FORMAT,
  OWL_ERROR_UNKNOWN
};

#endif
