#ifndef OWL_CLIENT_H_
#define OWL_CLIENT_H_

#include "types.h"

struct owl_renderer_init_info;

struct owl_client_init_info {
  char const *title;
  owl_i32 width;
  owl_i32 height;
};

enum owl_button_state {
  OWL_BUTTON_STATE_NONE,
  OWL_BUTTON_STATE_PRESS,
  OWL_BUTTON_STATE_RELEASE,
  OWL_BUTTON_STATE_REPEAT
};

enum owl_mouse_button {
  OWL_MOUSE_BUTTON_LEFT,
  OWL_MOUSE_BUTTON_MIDDLE,
  OWL_MOUSE_BUTTON_RIGHT,
  OWL_MOUSE_BUTTON_COUNT
};

enum owl_keyboard_key {
  /* Printable keys */
  OWL_KEYBOARD_KEY_SPACE = 32,
  OWL_KEYBOARD_KEY_APOSTROPHE = 39,
  OWL_KEYBOARD_KEY_COMMA = 44,
  OWL_KEYBOARD_KEY_MINUS = 45,
  OWL_KEYBOARD_KEY_PERIOD = 46,
  OWL_KEYBOARD_KEY_SLASH = 47,
  OWL_KEYBOARD_KEY_0 = 48,
  OWL_KEYBOARD_KEY_1 = 49,
  OWL_KEYBOARD_KEY_2 = 50,
  OWL_KEYBOARD_KEY_3 = 51,
  OWL_KEYBOARD_KEY_4 = 52,
  OWL_KEYBOARD_KEY_5 = 53,
  OWL_KEYBOARD_KEY_6 = 54,
  OWL_KEYBOARD_KEY_7 = 55,
  OWL_KEYBOARD_KEY_8 = 56,
  OWL_KEYBOARD_KEY_9 = 57,
  OWL_KEYBOARD_KEY_SEMICOLON = 59,
  OWL_KEYBOARD_KEY_EQUAL = 61,
  OWL_KEYBOARD_KEY_A = 65,
  OWL_KEYBOARD_KEY_B = 66,
  OWL_KEYBOARD_KEY_C = 67,
  OWL_KEYBOARD_KEY_D = 68,
  OWL_KEYBOARD_KEY_E = 69,
  OWL_KEYBOARD_KEY_F = 70,
  OWL_KEYBOARD_KEY_G = 71,
  OWL_KEYBOARD_KEY_H = 72,
  OWL_KEYBOARD_KEY_I = 73,
  OWL_KEYBOARD_KEY_J = 74,
  OWL_KEYBOARD_KEY_K = 75,
  OWL_KEYBOARD_KEY_L = 76,
  OWL_KEYBOARD_KEY_M = 77,
  OWL_KEYBOARD_KEY_N = 78,
  OWL_KEYBOARD_KEY_O = 79,
  OWL_KEYBOARD_KEY_P = 80,
  OWL_KEYBOARD_KEY_Q = 81,
  OWL_KEYBOARD_KEY_R = 82,
  OWL_KEYBOARD_KEY_S = 83,
  OWL_KEYBOARD_KEY_T = 84,
  OWL_KEYBOARD_KEY_U = 85,
  OWL_KEYBOARD_KEY_V = 86,
  OWL_KEYBOARD_KEY_W = 87,
  OWL_KEYBOARD_KEY_X = 88,
  OWL_KEYBOARD_KEY_Y = 89,
  OWL_KEYBOARD_KEY_Z = 90,
  OWL_KEYBOARD_KEY_LEFT_BRACKET = 91 /* [ */,
  OWL_KEYBOARD_KEY_BACKSLASH = 92 /* \ */,
  OWL_KEYBOARD_KEY_RIGHT_BRACKET = 93 /* ] */,
  OWL_KEYBOARD_KEY_GRAVE_ACCENT = 96 /* ` */,
  OWL_KEYBOARD_KEY_WORLD_1 = 161 /* non-US #1 */,
  OWL_KEYBOARD_KEY_WORLD_2 = 162 /* non-US #2 */,
  /* Function keys */
  OWL_KEYBOARD_KEY_ESCAPE = 256,
  OWL_KEYBOARD_KEY_ENTER = 257,
  OWL_KEYBOARD_KEY_TAB = 258,
  OWL_KEYBOARD_KEY_BACKSPACE = 259,
  OWL_KEYBOARD_KEY_INSERT = 260,
  OWL_KEYBOARD_KEY_DELETE = 261,
  OWL_KEYBOARD_KEY_RIGHT = 262,
  OWL_KEYBOARD_KEY_LEFT = 263,
  OWL_KEYBOARD_KEY_DOWN = 264,
  OWL_KEYBOARD_KEY_UP = 265,
  OWL_KEYBOARD_KEY_PAGE_UP = 266,
  OWL_KEYBOARD_KEY_PAGE_DOWN = 267,
  OWL_KEYBOARD_KEY_HOME = 268,
  OWL_KEYBOARD_KEY_END = 269,
  OWL_KEYBOARD_KEY_CAPS_LOCK = 280,
  OWL_KEYBOARD_KEY_SCROLL_LOCK = 281,
  OWL_KEYBOARD_KEY_NUM_LOCK = 282,
  OWL_KEYBOARD_KEY_PRINT_SCREEN = 283,
  OWL_KEYBOARD_KEY_PAUSE = 284,
  OWL_KEYBOARD_KEY_F1 = 290,
  OWL_KEYBOARD_KEY_F2 = 291,
  OWL_KEYBOARD_KEY_F3 = 292,
  OWL_KEYBOARD_KEY_F4 = 293,
  OWL_KEYBOARD_KEY_F5 = 294,
  OWL_KEYBOARD_KEY_F6 = 295,
  OWL_KEYBOARD_KEY_F7 = 296,
  OWL_KEYBOARD_KEY_F8 = 297,
  OWL_KEYBOARD_KEY_F9 = 298,
  OWL_KEYBOARD_KEY_F10 = 299,
  OWL_KEYBOARD_KEY_F11 = 300,
  OWL_KEYBOARD_KEY_F12 = 301,
  OWL_KEYBOARD_KEY_F13 = 302,
  OWL_KEYBOARD_KEY_F14 = 303,
  OWL_KEYBOARD_KEY_F15 = 304,
  OWL_KEYBOARD_KEY_F16 = 305,
  OWL_KEYBOARD_KEY_F17 = 306,
  OWL_KEYBOARD_KEY_F18 = 307,
  OWL_KEYBOARD_KEY_F19 = 308,
  OWL_KEYBOARD_KEY_F20 = 309,
  OWL_KEYBOARD_KEY_F21 = 310,
  OWL_KEYBOARD_KEY_F22 = 311,
  OWL_KEYBOARD_KEY_F23 = 312,
  OWL_KEYBOARD_KEY_F24 = 313,
  OWL_KEYBOARD_KEY_F25 = 314,
  OWL_KEYBOARD_KEY_KP_0 = 320,
  OWL_KEYBOARD_KEY_KP_1 = 321,
  OWL_KEYBOARD_KEY_KP_2 = 322,
  OWL_KEYBOARD_KEY_KP_3 = 323,
  OWL_KEYBOARD_KEY_KP_4 = 324,
  OWL_KEYBOARD_KEY_KP_5 = 325,
  OWL_KEYBOARD_KEY_KP_6 = 326,
  OWL_KEYBOARD_KEY_KP_7 = 327,
  OWL_KEYBOARD_KEY_KP_8 = 328,
  OWL_KEYBOARD_KEY_KP_9 = 329,
  OWL_KEYBOARD_KEY_KP_DECIMAL = 330,
  OWL_KEYBOARD_KEY_KP_DIVIDE = 331,
  OWL_KEYBOARD_KEY_KP_MULTIPLY = 332,
  OWL_KEYBOARD_KEY_KP_SUBTRACT = 333,
  OWL_KEYBOARD_KEY_KP_ADD = 334,
  OWL_KEYBOARD_KEY_KP_ENTER = 335,
  OWL_KEYBOARD_KEY_KP_EQUAL = 336,
  OWL_KEYBOARD_KEY_LEFT_SHIFT = 340,
  OWL_KEYBOARD_KEY_LEFT_CONTROL = 341,
  OWL_KEYBOARD_KEY_LEFT_ALT = 342,
  OWL_KEYBOARD_KEY_LEFT_SUPER = 343,
  OWL_KEYBOARD_KEY_RIGHT_SHIFT = 344,
  OWL_KEYBOARD_KEY_RIGHT_CONTROL = 345,
  OWL_KEYBOARD_KEY_RIGHT_ALT = 346,
  OWL_KEYBOARD_KEY_RIGHT_SUPER = 347,
  OWL_KEYBOARD_KEY_MENU = 348
};

#define OWL_KEYBOARD_KEY_LAST OWL_KEYBOARD_KEY_MENU

struct owl_client {
  char const *title;
  void *window;
  owl_i32 framebuffer_width;
  owl_i32 framebuffer_height;
  owl_i32 window_width;
  owl_i32 window_height;
  double fps;
  double d_time_stamp;
  double time_stamp;
  double previous_time_stamp;
  owl_v2 d_cursor_position;
  owl_v2 cursor_position;
  owl_v2 previous_cursor_position;
  enum owl_button_state mouse_buttons[OWL_MOUSE_BUTTON_COUNT];
  enum owl_button_state keyboard_keys[OWL_KEYBOARD_KEY_LAST];
};

enum owl_code owl_client_init(struct owl_client_init_info const *cii,
                              struct owl_client *c);

void owl_client_deinit(struct owl_client *c);

enum owl_code
owl_client_fill_renderer_init_info(struct owl_client const *c,
                                   struct owl_renderer_init_info *rii);

void owl_client_poll_events(struct owl_client *c);

owl_i32owl_client_is_done(struct owl_client *c);

#endif
