#ifndef OWL_EVENT_QUEUE_H_
#define OWL_EVENT_QUEUE_H_

enum owl_event_type {
  OWL_EVENT_TYPE_NONE,
  OWL_EVENT_TYPE_WINDOW_MOVED,
  OWL_EVENT_TYPE_WINDOW_RESIZED,
  OWL_EVENT_TYPE_WINDOW_CLOSED,
  OWL_EVENT_TYPE_WINDOW_REFRESH,
  OWL_EVENT_TYPE_WINDOW_FOCUSED,
  OWL_EVENT_TYPE_WINDOW_DEFOCUSED,
  OWL_EVENT_TYPE_WINDOW_ICONIFIED,
  OWL_EVENT_TYPE_WINDOW_UNICONIFIED,
  OWL_EVENT_TYPE_FRAMEBUFFER_RESIZED,
  OWL_EVENT_TYPE_BUTTON_PRESSED,
  OWL_EVENT_TYPE_BUTTON_RELEASED,
  OWL_EVENT_TYPE_CURSOR_MOVED,
  OWL_EVENT_TYPE_CURSOR_ENTERED,
  OWL_EVENT_TYPE_CURSOR_LEFT,
  OWL_EVENT_TYPE_SCROLLED,
  OWL_EVENT_TYPE_KEY_PRESSED,
  OWL_EVENT_TYPE_KEY_REPEATED,
  OWL_EVENT_TYPE_KEY_RELEASED,
  OWL_EVENT_TYPE_CODEPOINT_INPUT,
  OWL_EVENT_TYPE_MONITOR_CONNECTED,
  OWL_EVENT_TYPE_MONITOR_DISCONNECTED
};

struct owl_event {};

struct owl_event_queue {
  int empty;
};

#endif
