glslangValidator -V -x -o basic_vertex.spv.u32 basic.vert
glslangValidator -V -x -o basic_fragment.spv.u32 basic.frag
glslangValidator -V -x -o font_fragment.spv.u32 font.frag
glslangValidator -V -x -o pbr_vertex.spv.u32 pbr.vert
glslangValidator -V -x -o pbr_fragment.spv.u32 pbr.frag
glslangValidator -V -x -o skybox_vertex.spv.u32 skybox.vert
glslangValidator -V -x -o skybox_fragment.spv.u32 skybox.frag
glslangValidator -V -x -o brdflut_vertex.spv.u32 brdflut.vert
glslangValidator -V -x -o brdflut_fragment.spv.u32 brdflut.frag
glslangValidator -V -x -o irradiance_cube_fragment.spv.u32 irradiance_cube.frag
glslangValidator -V -x -o prefiltered_cube_vertex.spv.u32 prefiltered_cube.vert
glslangValidator -V -x -o prefiltered_cube_fragment.spv.u32 prefiltered_cube.frag
