glslangValidator -V -x -o basic_vertex.spv.u32 basic.vert
glslangValidator -V -x -o basic_fragment.spv.u32 basic.frag
glslangValidator -V -x -o font_fragment.spv.u32 font.frag
glslangValidator -V -x -o skybox_vertex.spv.u32 skybox.vert
glslangValidator -V -x -o skybox_fragment.spv.u32 skybox.frag
glslangValidator -V -x -o scene_vertex.spv.u32 scene.vert
glslangValidator -V -x -o scene_fragment.spv.u32 scene.frag
glslangValidator -V -x -o model_vertex.spv.u32 model.vert
glslangValidator -V -x -o model_fragment.spv.u32 model.frag
